name: Build, Test, and Lint
on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - .vscode/**
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .vscode/**

jobs:
  test:
    timeout-minutes: 30
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Run lint
        run: pnpm lint
